version: '3.8'  # Explicit version for better compatibility
services:
  jenkins_master:
    image: jenkins/jenkins:lts  # Using LTS version for stability
    ports:
      - "8080:8080"  # Web UI port
      - "50000:50000"  # Agent communication port
    volumes:
      - "/home/linuxgr8/jenkins-multi-node-docker/jenkins_master:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allows Jenkins to run Docker commands
    networks:
      - jenkins
    restart: unless-stopped  # Auto-restart policy for reliability

  jenkins_agent1:
    build: .
    image: rajatkm93/ssh-agent:latest #Add your docker hub repo
    ports:
      - "50000"  # Agent communication port
    volumes:
      - "/home/linuxgr8/jenkins-multi-node-docker/jenkins_agent1:/home/jenkins" 
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allows Jenkins to run Docker commands
    networks:
      - jenkins
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'  # CPU limit
          memory: 512M  # Memory limit

  jenkins_agent2:
    build: .
    image: rajatkm93/ssh-agent:latest #Add your docker hub repo
    ports:
      - "50000"  # Agent communication port
    volumes:
      - "/home/linuxgr8/jenkins-multi-node-docker/jenkins_agent2:/home/jenkins" 
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allows Jenkins to run Docker commands
    networks:
      - jenkins
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'  # CPU limit
          memory: 512M  # Memory limit

networks:
  jenkins:
    driver: bridge
    attachable: true  # Allows containers to attach after creation
